services:
  mongo:
    image: mongo:6
    container_name: smartphotosorter-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example123
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://root:example123@mongo:27017/?authSource=admin
      JWT_SECRET: "supersecret"
    depends_on:
      - mongo
    volumes:
      - ./backend/app/storage:/app/app/storage
      -  /home/you/Pictures:/data
volumes:
  mongo_data:
